name: CI for main branch

on:
  push:
    branches:
      - 'main'

jobs:
  # See https://stackoverflow.com/a/73624365/16109047
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'velut/gridify.it' && github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Check
        run: bun run check

      - name: Build
        run: bun run build

      - name: Deploy to Bunny.net
        run: bun run bunny:deploy
        env:
          BUNNY_API_KEY: ${{ secrets.BUNNY_API_KEY }}
          BUNNY_PULL_ZONE_ID: ${{ secrets.BUNNY_PULL_ZONE_ID }}
          BUNNY_STORAGE_ZONE_HOSTNAME: ${{ secrets.BUNNY_STORAGE_ZONE_HOSTNAME }}
          BUNNY_STORAGE_ZONE_NAME: ${{ secrets.BUNNY_STORAGE_ZONE_NAME }}
          BUNNY_STORAGE_ZONE_PASSWORD: ${{ secrets.BUNNY_STORAGE_ZONE_PASSWORD }}
