name: CI for main branch

on:
  push:
    branches:
      - 'main'

jobs:
  # See https://stackoverflow.com/a/73624365/16109047
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'velut/gridify.it' && github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Ensure `src/licenses.json` exists
        run: pnpm licenses:ensure

      - name: Lint
        run: pnpm lint

      - name: Check
        run: pnpm check

      - name: Build
        run: pnpm build

      - name: Deploy to Bunny.net
        run: pnpm bunny:deploy
        env:
          BUNNY_API_KEY: ${{ secrets.BUNNY_API_KEY }}
          BUNNY_STORAGE_ZONE_HOSTNAME: ${{ secrets.BUNNY_STORAGE_ZONE_HOSTNAME }}
          BUNNY_STORAGE_ZONE_NAME: ${{ secrets.BUNNY_STORAGE_ZONE_NAME }}
          BUNNY_STORAGE_ZONE_PASSWORD: ${{ secrets.BUNNY_STORAGE_ZONE_PASSWORD }}
          BUNNY_PULL_ZONE_NAME: ${{ secrets.BUNNY_PULL_ZONE_NAME }}
